### ISSUE TITLE
Migrate to new react (18)

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#209]
We need to migrate to the newest react.

Consider and write info here about:
- using Typescript when changing something 
- writing some info useful for upgrade of record-manager
- using new features/best practices of react (i.e. design what to rewrite now or later)

A/C:
- version of react is changed to 18
- all github security updates are merged
- it is tested manually
- new minor version is released

**Comment by blcham** [comment]
Btw, testing framework enzyme is not supported in react 18.

**Comment by VojtechLunak** [comment]
With React upgraded to v 18.2.0, these warnings occur:
- optional peer dependencies for React ^17.0.0
    - @luigiminardim/storybook-addon-globals-controls@0.1.3
    - @storybook/addon-a11y@6.4.19
    - @storybook/addon-actions@6.4.19
    - @storybook/addon-essentials@6.4.19
    - @storybook/addon-interactions@6.4.19
    - @storybook/addon-jest@6.4.19
    - @storybook/addon-links@6.4.19
-  peer dependencies
   - @storybook/react@6.4.19
   - @storybook/testing-react@1.2.4
   - @wojtekmaj/enzyme-adapter-react-17@0.6.6
   - react-datepicker@4.7.0
   - react-intl@5.24.7
   - react-loader-spinner@5.1.4
   - react-select@3.2.0
   - react-window@1.8.6

**Comment by blcham** [comment]
Current state: enzyme is upgraded.
Next: try to use storybook-addon-globals-controls@0.1.3, here is an issue https://github.com/luigiminardim/storybook-addon-globals-controls/issues/4

**Comment by VojtechLunak** [comment]
## Enzyme
With further investigation [(1)](https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl)[(2)](https://github.com/enzymejs/enzyme/issues/2524) into Enzyme and React 17 / React 18 enzyme adapter, I think the tests will need migration from using Enzyme into another library (for example [react-testing-library](https://testing-library.com/docs/react-testing-library/intro)). In the current state 11 tests (only from `Answer.test.js`) do not pass because of the unofficial adapter for React 18, which does not work exactly as adapter for React 17.

## Storybook  & global controls
After further investigation, it seems the storybook stories would benefit from refactoring them into the [newest scenario format](https://storybook.js.org/docs/react/api/csf#upgrading-from-csf-2-to-csf-3).  The reason is more efficient decorator application (Applying react context providers to components).

As storybook-addon-globals-controls@0.1.3 is not compatible with Storybook 7, I looked into handling globals and it seems that storybook has its own built-in [globals and toolbars](https://storybook.js.org/docs/react/essentials/toolbars-and-globals) mechanism.

**Comment by blcham** [comment]
@VojtechLunak great job so far. I agree with storybook ideas and netlify fix. W.r.t. enzyme i cannot judge what is most appropriate library switch so i guess it is fine as well.

**Comment by VojtechLunak** [comment]
Storybook scenario sections refactor. 
Stories (Sforms) vs Components.
