### ISSUE TITLE
Values in typeahead are dissapearing from the dropdown in storybook

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#218]
![image](https://github.com/kbss-cvut/s-forms/assets/3962237/deaf5e81-831c-4cbc-8b38-6fc9d5376c36)

It behaves as follows:
- when I select 3 ---> 0 is missing
- when I select 4 ---> 0,1 is missing
- when I select "Not allowed" ---> 0,1,2 is missing

Tested on:
https://deploy-preview-217--s-forms-kbss.netlify.app/?path=/story/stories-forms--tourist-destination-form-2&globals=locale:cs;timeOut:200

**Comment by VojtechLunak** [comment]
Seems that this issue was also in PR https://github.com/kbss-cvut/s-forms/pull/203. [Storybook preview](https://deploy-preview-203--s-forms-kbss.netlify.app/?path=/story/sforms--tourist-destination-form-2)

Might be related to the form.

Also, in current storybook preview - [storybook](https://s-forms-kbss.netlify.app/)

**Comment by blcham** [comment]
Closing, solved by https://github.com/kbss-cvut/s-forms/pull/232
