### ISSUE TITLE
Section can be collapsed while checkbox still ticked

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/s-forms#49]
When the chechbox is ticked to expand a section, it is possible to collapse the section by clicking on the bar of the question instead of the checkbox itself, leaving the checkbox ticked.

![Capture d’écran 2021-07-13 112555](https://user-images.githubusercontent.com/57750426/125427633-0b359474-4bbb-47b3-855b-812e044e4e65.png)

**Comment by blcham** [comment]
Thank you ! for the issue opening -- but in this case it is expected behaviour.  It is however useful to know it is a little confusing to you.

Let's say we have answerable section "Person". Semantics of the question is :
- if Person answerable section is true it means there is a Person (even without specifying any of its subquestions such as Firstname, Lastname)
- if Person answerable section is false it means there is no such a Person

In addition, each section is collapsable (i.e. to save space on the screen when filling the form user can decide to collapse the section.)

**Comment by blcham** [comment]
If it is clear, please close this issue.
